### PR TITLE
Content-Type header parser

### LINKED ISSUE #257: multipart/form-data broken on new firefox version
Multipart forms seem to be broken in new firefox versions, no idea why. It works in chromium, qtwebkit and firefox 128 ESR but it seems like something changed in a new version. I looked at the difference between the form format for between firefox versions but they seem the same. Here's a minimal example:
```nim
import prologue

const page = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <form action="/upload" method="post" enctype="multipart/form-data">
        <input type="file" name="image">
        <button type="submit">Upload</button>
    </form>
</body>
</html>"""

proc form(ctx: Context) {.async.} =
    resp htmlResponse(page)
    
proc upload(ctx: Context) {.async.} =
    try:
        let f = ctx.request.formParams["image"]
        if f.body.len == 0:
            resp "<h1>File upload is empty.</h1>"
        else:
            resp "<h1>Success, filename: " & f.params["filename"] & "</h1>"
    except KeyError:
        resp "<h1>Error, param 'image' not found.</h1>"

var app = newApp()
app.addRoute("/", form)
app.addRoute("/upload", upload, HttpPost)
app.run()
```
Will always respond with the error on firefox 135

### PR DESCRIPTION
**Pull request by nnsee**
This fixes #257.

Added a spec-compliant (as far as I can tell) header parser for the Content-Type header, specifically in regards to the `boundary` param. Also added some tests for the new parser and `form.nim`.

### CODE REVIEW

**Comment by nnsee** [comment]
I don't know why the tests fail. It also fails on devel even without my changes. And the process seems to hang.

**Comment by ringabout** [comment]
The devel actually passes the tests because circle CI is unused though it still causes failures. I guess there is a loop which causes the hang

**Comment by PhilippMDoerner** [comment]
Out of curiosity, what blocks this? A fix for the test-suite?

**Comment by ringabout** [comment]
I think so. Besides, I could merge a workaround PR to replace `rfind` with `find` => https://github.com/planety/prologue/pull/260

**Comment by nnsee** [comment]
I don't think the test suite issue is from my side, try to run the test suite on just the master branch of this repo and see if it exhibits the same behavior, I'm pretty sure it does.

**Comment by ringabout** [comment]
It seems that https://github.com/planety/prologue/pull/263 the cookie dep causes the hang

File: src/prologue/core/contenttype.nim [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+
+proc `$`*(mediaType: MediaType): string =
+  ## Convert MediaType to string representation
+  result = mediaType.mainType & "/" & mediaType.subType
+
+  for name, value in mediaType.parameters:
+    var needsQuotes = false
+    for c in value:
+      # valid token characters as per RFC 7230 section 3.2.6
+      if not (c in {'a'..'z', 'A'..'Z', '0'..'9',
```
Comment (PhilippMDoerner) [inline src/prologue/core/contenttype.nim]: Generally I'd recommend having a const with that set (could be in global scope in this file as it does not necessarily need to be anywhere else) so if doesn't need to be generated all the time and can have a speaking name.
For example:
```nim
 # Token Characters as per RFC 7230 section 3.2.6 (link maybe?)
const VALID_TOKEN_CHARACTERS = ... the set ...
```

File: src/prologue/core/contenttype.nim [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+  var
+    i = 0
+    headerLen = headerValue.len
+
+  while i < headerLen and headerValue[i] in Whitespace:
+    inc i
+
+  # media type
+  let mediaTypeStart = i
+  while i < headerLen and headerValue[i] notin {';', ' ', '\t'}:
```
Comment (PhilippMDoerner) [inline src/prologue/core/contenttype.nim:40]: Would it be correct to put this in a variable with a speaking name, i.e.:
`const MEDIA_TYPE_TERMINATORS = {';', ' ', '\t'}`
?

**Comment by PhilippMDoerner** [comment]
I think before I go any deeper into this: I'm happy to do a codereview here, if my style of code that I tend to strive for and find most readable works for y'all.

As in, I am very thankful you took the time to implement this Ras, I'd just love to split a few things out for example to have a few smaller procs that do individual tasks like a "parseMediaType" proc that returns a parsed media-type and media-type start- and end-indexes etc.
My goal there would be that ideally you don't need to know the RFCs to understand the code, the variable names and proc names tell you everything you need while isolating smaller individual tasks.

However, if that looks like it does more work than it's worth I'm happy to drop that.

File: src/prologue/core/contenttype.nim [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+proc `$`*(mediaType: MediaType): string =
+  ## Convert MediaType to string representation
+  result = mediaType.mainType & "/" & mediaType.subType
+
+  for name, value in mediaType.parameters:
+    var needsQuotes = false
+    for c in value:
+      # valid token characters as per RFC 7230 section 3.2.6
+      if not (c in {'a'..'z', 'A'..'Z', '0'..'9',
+                    '!', '#', '$', '%', '&', '\'', '*', '+', '-', '.', '^', '_', '`', '|', '~'}):
```
Comment (ringabout) [inline src/prologue/core/contenttype.nim]:
```suggestion
      if c notin {'a'..'z', 'A'..'Z', '0'..'9',
                    '!', '#', '$', '%', '&', '\'', '*', '+', '-', '.', '^', '_', '`', '|', '~'}:
```

**Review by ringabout — APPROVED** [review]
Nice work!

File: src/prologue/core/contenttype.nim [hunk 4]
```diff
@@ -0,0 +1,113 @@
+import std/[strutils, tables, strformat]
+
+type
+  MediaType* = object
+    mainType*: string
+    subType*: string
+    parameters*: Table[string, string]
+
+proc parseContentType*(headerValue: string): MediaType =
+  ## Parses a Content-Type header according to RFC 7230, RFC 2045, and RFC 2046.
```
Comment (PhilippMDoerner) [inline src/prologue/core/contenttype.nim:22]: Could be nice to add an example string with parameters just to give the reader an idea of what kind of string is being parsed without having to read the RFCs

File: src/prologue/core/contenttype.nim (hunk 2 above)
Comment (PhilippMDoerner) [reply src/prologue/core/contenttype.nim:40]: That wouldn't necessarily improve that much in terms of readability so imo... meh

File: src/prologue/core/contenttype.nim [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+    if i >= headerLen or headerValue[i] != '=':
+      # this is a malformed parameter - skip it
+      while i < headerLen and headerValue[i] != ';':
+        inc i
+      continue
+
+    let paramName = headerValue[paramNameStart..<i].strip().toLowerAscii()
+    inc i
+
+    while i < headerLen and headerValue[i] in Whitespace:
```
Comment (PhilippMDoerner) [inline src/prologue/core/contenttype.nim]: Given how often this occurs you *could* outsource this into a proc:
```nim
proc skipNextWhitespacesIn(i: var int, headerValue: string) =
  while i < headerValue.len and headerValue[i] in Whitespace:
    inc i

#example usage:
i.skipNextWhitespacesIn(headerValue)
 ```

I'm not sure myself how much that improves readability so I'll leave it to you to decide if that actually improves readability.

File: src/prologue/core/contenttype.nim [hunk 6]
```diff
@@ -0,0 +1,113 @@
...
+      inc i
+
+proc `$`*(mediaType: MediaType): string =
+  ## Convert MediaType to string representation
+  result = mediaType.mainType & "/" & mediaType.subType
+
+  for name, value in mediaType.parameters:
+    var needsQuotes = false
```
Comment (PhilippMDoerner) [inline src/prologue/core/contenttype.nim]: If you want a more convenient shorthand here:

```nim
let needsQuotes = value.anyIt(it notin VALID_TOKEN_CHARACTERS)
```

File: src/prologue/core/form.nim [hunk 7]
```diff
@@ -89,18 +96,19 @@ func parseFormPart*(body, contentType: string): FormPart =
...
+
+  if mediaType.mainType == "application" and mediaType.subType == "x-www-form-urlencoded":
     request.formParams = initFormPart()
     if request.reqMethod == HttpPost:
       for (key, value) in decodeQuery(request.body):
         # formPrams and postParams for secret event
         request.formParams[key] = value
         request.postParams[key] = value
-  elif "multipart/form-data" in contentType and "boundary" in contentType:
+  elif mediaType.mainType == "multipart" and mediaType.subType == "form-data" and "boundary" in mediaType.parameters:
```
Comment (PhilippMDoerner) [inline src/prologue/core/form.nim:108]: Could put this in its own proc:

```nim
# contenttype.nim
proc isApplicationUrlEndedForm*(x: MediaType): bool =
  x.mainType == "application" and x.subType == "x-www-form-urlencoded"

proc isMultipartFormdata*(x: MediaType): bool =
  x.mainType == "multipart" and x.subType == "form-data"

proc hasParam*(x: MediaType, paramName: string): bool =
  paramName in x.parameters
....

#form.nim
...
if mediaType.isApplicationUrlEncodedForm():

elif mediaType.isMultipartFormdata() and mediaType.hasParam("boundary)
```

Again, just an optional suggestion from my own code style, doesn't need to be adhered to here, I think it's already alright to read as is.

**Comment by PhilippMDoerner** [comment]
Overall, LGTM. A couple suggestions that you can heed if you want to, I'll leave that up to you.

**Review by PhilippMDoerner — APPROVED** [review]

File: src/prologue/core/contenttype.nim (hunk 4 above)
Comment (nnsee) [reply src/prologue/core/contenttype.nim:22]: Would a `runnableExamples` be fine here?

Comment (PhilippMDoerner) [reply src/prologue/core/contenttype.nim:22]: That would actually be even better than what I thought, entirely forgot nim had those. Perfect idea!

**Comment by nnsee** [comment]
Thanks for the code review!
