### PR TITLE
Fix GET request params

### LINKED ISSUE #273: ERROR Malformed form params: Invalid media type: on GET request, no params available
This program fails to ever read the `query` param and also shows an error in the log:

```nim
import prologue

proc searchHandler(ctx: Context) {.async.} =
  let query = ctx.getQueryParamsOption("query").get("")
  resp "query: [" & query & "]\n"

let app = newApp()
app.get("/", searchHandler)
app.run()
```

```
$ curl 'http://127.0.0.1:8080/?query=hello'
query: []
```

```
# log
DEBUG Prologue is serving at http://0.0.0.0:8080 
DEBUG Starting 1 threads
ERROR Malformed form params:
Invalid media type: 
DEBUG GET /
DEBUG 200 OK {"content-type": @["text/html; charset=UTF-8"]}
DEBUG socket: 9 is closed!
```

It worked correctly in c3da4452732077652a6ebabb8b7365a65f300fbf. I believe 09ac7ac735606d20f7b2ee1afe478c5b840e2cd2 introduced the bug.

### PR DESCRIPTION
**Pull request by iffy**
Fixes #273

I don't know if this is the best fix, nor do I know how to run the tests, but this is my best attempt.

### CODE REVIEW

File: src/prologue/core/form.nim [hunk 1]
```diff
@@ -96,7 +96,10 @@ func parseFormPart*(body, contentType: string): FormPart =
 
 func parseFormParams*(request: var Request, contentType: string) =
   ## Parses get or post or query parameters.
-  let mediaType = parseContentType(contentType)
+  let mediaType = try:
+      parseContentType(contentType)
+    except:
```
Comment (ringabout) [inline src/prologue/core/form.nim]:
```suggestion
    except CatchableError:
```
